// The Council's grape ledger: every varietal a bottle may plausibly carry —
// the classics, the obscures, the Cape locals — plus blend and style
// categories for bottles whose exact composition is unknown. The detector
// reads them straight out of a wine's name (typos included — the annals
// spell Sauvignon three ways). The picker also accepts anything typed
// freehand, so an unlisted grape never blocks the Keiser.

const WHITES = [
  "Airén", "Albariño", "Aligoté", "Antão Vaz", "Arinto", "Arneis", "Assyrtiko",
  "Auxerrois", "Bical", "Bourboulenc", "Bukettraube", "Catarratto",
  "Chardonnay", "Chasselas", "Chenel", "Chenin Blanc", "Clairette", "Colombar",
  "Cortese", "Crouchen", "Encruzado", "Falanghina", "Fernão Pires", "Fiano",
  "Furmint", "Garganega", "Gewürztraminer", "Godello", "Grechetto", "Greco",
  "Grenache Blanc", "Grenache Gris", "Grillo", "Gros Manseng",
  "Grüner Veltliner", "Hanepoot", "Hárslevelű", "Jacquère", "Kerner",
  "Loureiro", "Malvasia", "Marsanne", "Mauzac", "Melon de Bourgogne",
  "Moschofilero", "Muscadelle", "Muscat", "Müller-Thurgau", "Nouvelle",
  "Palomino", "Pecorino", "Petit Manseng", "Picpoul", "Pinot Blanc",
  "Pinot Grigio", "Ribolla Gialla", "Riesling", "Rkatsiteli", "Roditis",
  "Roussanne", "Sauvignon Blanc", "Sauvignon Gris", "Savagnin", "Scheurebe",
  "Semillon", "Silvaner", "Timorasso", "Torrontés", "Trebbiano", "Treixadura",
  "Verdejo", "Verdelho", "Verdicchio", "Vermentino", "Viognier", "Viura",
  "Xarel·lo",
];

const REDS = [
  "Abouriou", "Agiorgitiko", "Aglianico", "Aleatico", "Alicante Bouschet",
  "Baga", "Barbera", "Blaufränkisch", "Bobal", "Bonarda", "Brachetto",
  "Cabernet Franc", "Cabernet Sauvignon", "Canaiolo", "Carignan", "Carmenère",
  "Castelão", "Cesanese", "Ciliegiolo", "Cinsault", "Corvina", "Counoise",
  "Dolcetto", "Dornfelder", "Duras", "Fer Servadou", "Frappato", "Freisa",
  "Gamay", "Graciano", "Grenache", "Grignolino", "Grolleau", "Lagrein",
  "Lambrusco", "Listán Negro", "Malbec", "Marselan", "Marzemino", "Mavrud",
  "Mencía", "Merlot", "Mondeuse", "Montepulciano", "Mourvèdre", "Nebbiolo",
  "Negroamaro", "Nerello Mascalese", "Nero d'Avola", "Négrette", "Pais",
  "Petit Verdot", "Petite Sirah", "Piedirosso", "Pineau d'Aunis", "Pinot Meunier",
  "Pinot Noir", "Pinotage", "Plavac Mali", "Poulsard", "Primitivo", "Refosco",
  "Rondinella", "Roobernet", "Ruby Cabernet", "Ruché", "Sagrantino",
  "Sangiovese", "Saperavi", "Schiava", "Sciacarello", "Souzao", "St. Laurent",
  "Susumaniello", "Syrah", "Tannat", "Tempranillo", "Teroldego",
  "Tinta Barocca", "Touriga Franca", "Touriga Nacional", "Trepat", "Trousseau",
  "Uva di Troia", "Vespolina", "Xinomavro", "Zinfandel", "Zweigelt",
];

// Blends and styles: for bottles whose exact grapes are unknown, or whose
// style IS the point. They travel through stats like any varietal.
export const STYLES = [
  "Red Blend", "White Blend", "Rosé", "Bordeaux Blend", "Rhône Blend",
  "Cape Blend", "GSM", "Field Blend", "Sparkling / MCC", "Port-style",
  "Dessert / Late Harvest", "Orange / Skin Contact",
];

export const GRAPES: string[] = [...WHITES, ...REDS, ...STYLES];

// The Unexplored draws from this curated shortlist, so its suggestions are
// nights the Council could actually convene — not alphabetical trivia.
export const NOTABLE: string[] = [
  "Gamay", "Nebbiolo", "Malbec", "Tempranillo", "Sangiovese", "Barbera",
  "Zinfandel", "Grüner Veltliner", "Albariño", "Gewürztraminer", "Semillon",
  "Verdelho", "Tannat", "Carmenère", "Petit Verdot", "Mourvèdre", "Marsanne",
  "Roussanne", "Fiano", "Assyrtiko", "Furmint", "Blaufränkisch", "Zweigelt",
  "Verdejo", "Vermentino", "Touriga Nacional", "Mencía", "Godello",
  "Montepulciano", "Nero d'Avola", "Aglianico", "Xinomavro", "Pinot Blanc",
  "Counoise", "Carignan", "GSM", "Cape Blend", "Bordeaux Blend",
  "Orange / Skin Contact", "Sparkling / MCC", "Rosé",
];

// By the Keiser's decree (2026-07-09): the Unexplored may NEVER suggest
// Hanepoot or any other dessert-leaning pour. Tag them, drink them if some
// soul dares bring one — but the vine does not recommend them.
export const NEVER_SUGGEST = new Set([
  "Hanepoot", "Muscat", "Muscadelle", "Aleatico", "Brachetto", "Zibibbo",
  "Dessert / Late Harvest", "Port-style",
]);

// Words (lowercase) that betray a grape inside a wine's name. Longer phrases
// are checked first and consumed, so "cabernet sauvignon" wins before bare
// "sauvignon" and "ruby cabernet" never collapses into Cabernet Sauvignon.
const ALIASES: [string, string][] = [
  // blends + styles (checked early: their names contain grape words)
  ["bordeaux blend", "Bordeaux Blend"],
  ["rhone blend", "Rhône Blend"],
  ["rhône blend", "Rhône Blend"],
  ["cape blend", "Cape Blend"],
  ["field blend", "Field Blend"],
  ["white blend", "White Blend"],
  ["red blend", "Red Blend"],
  ["gsm", "GSM"],
  ["cap classique", "Sparkling / MCC"],
  ["methode cap", "Sparkling / MCC"],
  ["mcc", "Sparkling / MCC"],
  ["champagne", "Sparkling / MCC"],
  ["blanc de blancs", "Sparkling / MCC"],
  ["cremant", "Sparkling / MCC"],
  ["crémant", "Sparkling / MCC"],
  ["prosecco", "Sparkling / MCC"],
  ["cava ", "Sparkling / MCC"],
  ["brut", "Sparkling / MCC"],
  ["noble late harvest", "Dessert / Late Harvest"],
  ["late harvest", "Dessert / Late Harvest"],
  ["straw wine", "Dessert / Late Harvest"],
  ["vin de paille", "Dessert / Late Harvest"],
  ["skin contact", "Orange / Skin Contact"],
  ["orange wine", "Orange / Skin Contact"],
  ["rosé", "Rosé"],
  // multi-word grapes and traps before their generic parts
  ["ruby cabernet", "Ruby Cabernet"],
  ["alicante bouschet", "Alicante Bouschet"],
  ["petite sirah", "Petite Sirah"],
  ["durif", "Petite Sirah"],
  ["pinot meunier", "Pinot Meunier"],
  ["pinot blanc", "Pinot Blanc"],
  ["grenache gris", "Grenache Gris"],
  ["grenache blanc", "Grenache Blanc"],
  ["grenache noir", "Grenache"],
  ["gruner veltliner", "Grüner Veltliner"],
  ["grüner veltliner", "Grüner Veltliner"],
  ["gruner", "Grüner Veltliner"],
  ["weisser riesling", "Riesling"],
  ["cape riesling", "Crouchen"],
  ["crouchen", "Crouchen"],
  ["tinta barocca", "Tinta Barocca"],
  ["tinta roriz", "Tempranillo"],
  ["touriga franca", "Touriga Franca"],
  ["touriga nacional", "Touriga Nacional"],
  ["touriga", "Touriga Nacional"],
  ["nero d'avola", "Nero d'Avola"],
  ["nero davola", "Nero d'Avola"],
  ["nerello mascalese", "Nerello Mascalese"],
  ["fernao pires", "Fernão Pires"],
  ["fernão pires", "Fernão Pires"],
  ["melon de bourgogne", "Melon de Bourgogne"],
  ["muscadet", "Melon de Bourgogne"],
  ["gros manseng", "Gros Manseng"],
  ["petit manseng", "Petit Manseng"],
  ["sauvignon gris", "Sauvignon Gris"],
  ["cabernet sauvignon", "Cabernet Sauvignon"],
  ["cab sav", "Cabernet Sauvignon"],
  ["cabernet franc", "Cabernet Franc"],
  ["pinot noir", "Pinot Noir"],
  ["pinot grigio", "Pinot Grigio"],
  ["pinot gris", "Pinot Grigio"],
  ["chenin blanc", "Chenin Blanc"],
  ["sauvignon blanc", "Sauvignon Blanc"],
  ["savignon blanc", "Sauvignon Blanc"],
  ["petit verdot", "Petit Verdot"],
  ["uva di troia", "Uva di Troia"],
  ["nero di troia", "Uva di Troia"],
  ["listan negro", "Listán Negro"],
  ["plavac mali", "Plavac Mali"],
  ["pineau d'aunis", "Pineau d'Aunis"],
  ["fer servadou", "Fer Servadou"],
  ["st laurent", "St. Laurent"],
  ["st. laurent", "St. Laurent"],
  ["antao vaz", "Antão Vaz"],
  ["antão vaz", "Antão Vaz"],
  ["ribolla gialla", "Ribolla Gialla"],
  ["ribolla", "Ribolla Gialla"],
  // single-word grapes (unambiguous)
  ["chenin", "Chenin Blanc"],
  ["chardonnay", "Chardonnay"],
  ["sauvignon", "Sauvignon Blanc"],
  ["savignon", "Sauvignon Blanc"],
  ["cabernet", "Cabernet Sauvignon"],
  ["riesling", "Riesling"],
  ["viognier", "Viognier"],
  ["semillon", "Semillon"],
  ["sémillon", "Semillon"],
  ["verdelho", "Verdelho"],
  ["colombar", "Colombar"],
  ["colombard", "Colombar"],
  ["muscat", "Muscat"],
  ["zibibbo", "Muscat"],
  ["hanepoot", "Hanepoot"],
  ["roussanne", "Roussanne"],
  ["marsanne", "Marsanne"],
  ["palomino", "Palomino"],
  ["clairette", "Clairette"],
  ["assyrtiko", "Assyrtiko"],
  ["albarino", "Albariño"],
  ["albariño", "Albariño"],
  ["alvarinho", "Albariño"],
  ["bukettraube", "Bukettraube"],
  ["chenel", "Chenel"],
  ["gewurztraminer", "Gewürztraminer"],
  ["gewürztraminer", "Gewürztraminer"],
  ["gewurz", "Gewürztraminer"],
  ["nouvelle", "Nouvelle"],
  ["picpoul", "Picpoul"],
  ["piquepoul", "Picpoul"],
  ["torrontes", "Torrontés"],
  ["torrontés", "Torrontés"],
  ["trebbiano", "Trebbiano"],
  ["ugni blanc", "Trebbiano"],
  ["vermentino", "Vermentino"],
  ["viura", "Viura"],
  ["macabeo", "Viura"],
  ["airen", "Airén"],
  ["airén", "Airén"],
  ["aligote", "Aligoté"],
  ["aligoté", "Aligoté"],
  ["arinto", "Arinto"],
  ["arneis", "Arneis"],
  ["auxerrois", "Auxerrois"],
  ["bical", "Bical"],
  ["bourboulenc", "Bourboulenc"],
  ["catarratto", "Catarratto"],
  ["chasselas", "Chasselas"],
  ["cortese", "Cortese"],
  ["encruzado", "Encruzado"],
  ["falanghina", "Falanghina"],
  ["fiano", "Fiano"],
  ["furmint", "Furmint"],
  ["garganega", "Garganega"],
  ["godello", "Godello"],
  ["grechetto", "Grechetto"],
  ["greco", "Greco"],
  ["grillo", "Grillo"],
  ["harslevelu", "Hárslevelű"],
  ["hárslevelű", "Hárslevelű"],
  ["jacquere", "Jacquère"],
  ["jacquère", "Jacquère"],
  ["kerner", "Kerner"],
  ["loureiro", "Loureiro"],
  ["malvasia", "Malvasia"],
  ["mauzac", "Mauzac"],
  ["moschofilero", "Moschofilero"],
  ["muscadelle", "Muscadelle"],
  ["muller-thurgau", "Müller-Thurgau"],
  ["müller-thurgau", "Müller-Thurgau"],
  ["pecorino", "Pecorino"],
  ["rkatsiteli", "Rkatsiteli"],
  ["roditis", "Roditis"],
  ["savagnin", "Savagnin"],
  ["scheurebe", "Scheurebe"],
  ["silvaner", "Silvaner"],
  ["sylvaner", "Silvaner"],
  ["timorasso", "Timorasso"],
  ["treixadura", "Treixadura"],
  ["verdejo", "Verdejo"],
  ["verdicchio", "Verdicchio"],
  ["xarel-lo", "Xarel·lo"],
  ["xarel·lo", "Xarel·lo"],
  ["xarello", "Xarel·lo"],
  ["pinotage", "Pinotage"],
  ["merlot", "Merlot"],
  ["malbec", "Malbec"],
  ["syrah", "Syrah"],
  ["shiraz", "Syrah"],
  ["grenache", "Grenache"],
  ["cannonau", "Grenache"],
  ["cinsault", "Cinsault"],
  ["cinsaut", "Cinsault"],
  ["mourvedre", "Mourvèdre"],
  ["mourvèdre", "Mourvèdre"],
  ["mouverde", "Mourvèdre"],
  ["monastrell", "Mourvèdre"],
  ["carignan", "Carignan"],
  ["tempranillo", "Tempranillo"],
  ["sangiovese", "Sangiovese"],
  ["nebbiolo", "Nebbiolo"],
  ["barbera", "Barbera"],
  ["zinfandel", "Zinfandel"],
  ["primitivo", "Primitivo"],
  ["souzao", "Souzao"],
  ["sousao", "Souzao"],
  ["tannat", "Tannat"],
  ["gamay", "Gamay"],
  ["aglianico", "Aglianico"],
  ["agiorgitiko", "Agiorgitiko"],
  ["aleatico", "Aleatico"],
  ["abouriou", "Abouriou"],
  ["baga", "Baga"],
  ["blaufrankisch", "Blaufränkisch"],
  ["blaufränkisch", "Blaufränkisch"],
  ["lemberger", "Blaufränkisch"],
  ["bobal", "Bobal"],
  ["bonarda", "Bonarda"],
  ["brachetto", "Brachetto"],
  ["canaiolo", "Canaiolo"],
  ["carmenere", "Carmenère"],
  ["carmenère", "Carmenère"],
  ["castelao", "Castelão"],
  ["castelão", "Castelão"],
  ["cesanese", "Cesanese"],
  ["ciliegiolo", "Ciliegiolo"],
  ["corvina", "Corvina"],
  ["counoise", "Counoise"],
  ["dolcetto", "Dolcetto"],
  ["dornfelder", "Dornfelder"],
  ["frappato", "Frappato"],
  ["freisa", "Freisa"],
  ["graciano", "Graciano"],
  ["grignolino", "Grignolino"],
  ["grolleau", "Grolleau"],
  ["lagrein", "Lagrein"],
  ["lambrusco", "Lambrusco"],
  ["marselan", "Marselan"],
  ["marzemino", "Marzemino"],
  ["mavrud", "Mavrud"],
  ["mencia", "Mencía"],
  ["mencía", "Mencía"],
  ["mondeuse", "Mondeuse"],
  ["montepulciano", "Montepulciano"],
  ["negroamaro", "Negroamaro"],
  ["negrette", "Négrette"],
  ["négrette", "Négrette"],
  ["piedirosso", "Piedirosso"],
  ["poulsard", "Poulsard"],
  ["refosco", "Refosco"],
  ["rondinella", "Rondinella"],
  ["roobernet", "Roobernet"],
  ["ruche", "Ruché"],
  ["ruché", "Ruché"],
  ["sagrantino", "Sagrantino"],
  ["saperavi", "Saperavi"],
  ["schiava", "Schiava"],
  ["sciacarello", "Sciacarello"],
  ["susumaniello", "Susumaniello"],
  ["teroldego", "Teroldego"],
  ["trepat", "Trepat"],
  ["trousseau", "Trousseau"],
  ["vespolina", "Vespolina"],
  ["xinomavro", "Xinomavro"],
  ["zweigelt", "Zweigelt"],
];

// Read the grapes out of a wine's name. "David & Nadia Grenache" → [Grenache];
// "Madison Barboulot Cabernet Syrah" → [Cabernet Sauvignon, Syrah].
export function detectVarietals(title: string): string[] {
  let low = ` ${title.toLowerCase()} `;
  const found: string[] = [];
  for (const [alias, grape] of ALIASES) {
    if (low.includes(alias)) {
      if (!found.includes(grape)) found.push(grape);
      low = low.split(alias).join(" "); // consume, so "cabernet sauvignon" doesn't also yield bare matches
    }
  }
  return found;
}
